### ISSUE TITLE
Refatorar para teste unitários

### ISSUE THREAD

**Issue by italo48** [fsmpinheiro/fine-pesq-EngSoft#14]
- [ ] Criar construtores e fazer as anotações @Autowired neles
- [ ] Tentar mudar todos os new's dentro do código

**Comment by Jataki** [comment]
Boas. Posso pegar?

**Comment by fsmpinheiro** [comment]
> 
> 
> Boas. Posso pegar?

Brother, agradeço a sua oferta, mas é trabalho de semestre aqui da faculdade. 
Então infelizmente não rola. Agradeço viu (y)
